version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/anuj-test
hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/start_portal_server.sh
    - location: deploy/start_hardware_server.sh
      timeout: 300
      runas: root